name: collaborator workflow
on:
  workflow_dispatch

jobs:
  collaborator-job:
    runs-on: ubuntu-latest

    steps:
      - name: request collaborator info
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/letsesign/workflow/collaborators/hylswind/permission
