name: witness workflow
on:
  workflow_dispatch:
    inputs:
      repo:
        description: github repository path
        required: true
        type: string
      issueNum:
        description: issue number
        required: true
        type: string
jobs:
  witness-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.0"
      - name: execute witeness procedure
        run: |
          cd src
          go build -o witness
          ./witness
        env:
          INPUT_REPO: ${{ inputs.repo }}
          INPUT_ISSUE_NUM: ${{ inputs.issueNum }}
